name: CI
"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install deps
        run: go install golang.org/x/tools/cmd/stringer@latest
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Race check
        run: make test-race
  lint:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
